apiVersion: apps/v1
kind: Deployment
metadata:
  name: p3-dev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
          
---

apiVersion: v1
kind: Service
metadata:
  name: p3-dev-service
spec:
  selector:
    app: wil-playground
  ports:
  - port: 80
    targetPort: 8888

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: p3-dev-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/dev"
        backend:
          service:
            name: p3-dev-service
            port:
              number: 80

